spring:
  application:
    name: metal-health-platform
    # 应用名称
  datasource:
    # 数据库连接URL，此处配置的是MySQL数据库
    url: jdbc:mysql://47.108.236.103:3306/mental_health_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    # MySQL数据库用户名，默认为root，请根据实际情况修改
    username: fangcun
    # MySQL数据库密码，此处示例为root，请根据实际情况修改
    password: fangcun123
    # 数据库驱动类，MySQL8.0+需要使用cj驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置，使用HikariCP连接池
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      ttl: 3600 # 缓存过期时间（秒）
  # Flyway 数据库迁移配置
  flyway:
    enabled: true  # 启用 Flyway，设置为true时启用
    baseline-on-migrate: true  # 当迁移时发现非空数据库，自动执行基线版本
    baseline-version: 0  # 基线版本设为0
    clean-disabled: true  # 禁用 clean 操作，防止误删数据库
    encoding: UTF-8  # 编码格式
    # SQL脚本文件名前缀，必须以大写V开头
    sql-migration-prefix: V
    # SQL脚本文件名分隔符，通常为两个下划线
    sql-migration-separator: __
    # SQL脚本文件后缀名
    sql-migration-suffixes: .sql
    locations: classpath:db/migration  # SQL脚本存放路径，通常在resources目录下
    table: flyway_schema_history  # Flyway版本历史记录表名
    validate-on-migrate: true # 迁移时验证脚本
    # 是否忽略缺失的迁移文件
    ignore-missing-migrations: true
  # MyBatis配置
mybatis:
  # Mapper XML文件路径，可以配置多个，使用通配符*匹配所有XML文件
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名包路径，简化XML中的类型配置
  type-aliases-package: sasu.platform.mhm.pojo.entity
  configuration:
    # 是否开启驼峰命名自动映射，将数据库中的下划线命名映射为Java的驼峰命名
    map-underscore-to-camel-case: true
    # MyBatis日志实现，此处配置为使用标准输出打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080

# 阿里云OSS配置（用于手写量表图片上传）
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com  # 例如: oss-cn-hangzhou.aliyuncs.com
    access-key-id: 1111
    access-key-secret: 111
    bucket-name: littleriver-web-tlias
    url-prefix: https://your-bucket-name.oss-cn-hangzhou.aliyuncs.com